import html2pdf from 'html2pdf.js';
import { format } from 'date-fns';
import { Vocabulary } from '@/types/vocabulary';

interface GeneratePdfOptions {
  vocabularies: Vocabulary[];
  userName: string;
  userEmail: string;
}

// Security: Sanitize HTML to prevent XSS
function sanitizeHTML(str: string): string {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

// Security: Escape special characters
function escapeHTML(str: string): string {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export const generateFavoritesPDF = async ({ vocabularies, userName, userEmail }: GeneratePdfOptions) => {
  try {
    // Security: Validate inputs
    if (!vocabularies || !Array.isArray(vocabularies)) {
      throw new Error('Invalid vocabularies data');
    }

    if (vocabularies.length === 0) {
      throw new Error('No vocabularies to export');
    }

    // Security: Limit number of vocabularies to prevent memory issues
    const MAX_VOCAB_COUNT = 1000;
    const safeVocabularies = vocabularies.slice(0, MAX_VOCAB_COUNT);

    // Create a temporary div for PDF content
    const pdfElement = document.createElement("div");
    pdfElement.id = "pdf-content";
    document.body.appendChild(pdfElement);

    // Security: Sanitize all user inputs
    const safeName = escapeHTML(userName || 'User');
    const safeEmail = escapeHTML(userEmail || 'N/A');
    const currentDate = format(new Date(), "PPP");
    const currentDateTime = new Date().toLocaleString();

    // Enhanced PDF content with better layout and SANITIZED data
    pdfElement.innerHTML = `
      <div class="report-container">
        <div class="header">
          <h1>Vocabulary Favorites</h1>
          <p class="tagline">Your personalized collection of words</p>
        </div>
        <div class="report-info">
          <div class="user-details">
            <p><strong>Name:</strong> ${safeName}</p>
            <p><strong>Email:</strong> ${safeEmail}</p>
            <p><strong>Export Date:</strong> ${currentDate}</p>
            <p><strong>Total Words:</strong> ${safeVocabularies.length}</p>
          </div>
        </div>

        <div class="vocab-list">
          ${safeVocabularies.map((vocab, index) => {
      // Security: Sanitize each vocabulary field
      const safeEnglish = escapeHTML(vocab.english || '');
      const safeBangla = escapeHTML(vocab.bangla || '');
      const safePos = escapeHTML(vocab.partOfSpeech || '');
      const safePronunciation = escapeHTML(vocab.pronunciation || '');
      const safeExample = vocab.example ? escapeHTML(vocab.example) : '';

      return `
            <div class="vocab-item">
              <div class="vocab-header">
                <span class="vocab-number">#${index + 1}</span>
                <span class="vocab-word">${safeEnglish}</span>
                <span class="vocab-pos">(${safePos})</span>
              </div>
              <div class="vocab-body">
                <p class="vocab-meaning"><strong>Meaning:</strong> ${safeBangla}</p>
                <p class="vocab-pronunciation"><strong>Pronunciation:</strong> ${safePronunciation}</p>
                ${safeExample ? `<p class="vocab-example"><strong>Example:</strong> "${safeExample}"</p>` : ''}
              </div>
            </div>
            `;
    }).join('')}
        </div>

        <div class="footer">
          <p>Generated by AI Vocabulary Coach</p>
          <p class="generated-at">Report created on ${currentDateTime}</p>
        </div>
      </div>
    `;

    // Optimized styles for better readability and print-friendliness
    const style = document.createElement('style');
    style.textContent = `
      .report-container {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        color: #333;
        background: #fff;
        line-height: 1.4;
      }
      .header {
        text-align: center;
        margin-bottom: 20px;
        border-bottom: 2px solid #2563eb;
        padding-bottom: 10px;
      }
      .header h1 {
        font-size: 28px;
        margin: 8px 0 4px 0;
        font-weight: 700;
        color: #2563eb;
      }
      .tagline {
        font-size: 14px;
        margin: 0;
        color: #6b7280;
        font-style: italic;
      }
      .report-info {
        margin-bottom: 20px;
      }
      .user-details {
        font-size: 13px;
        background: #f8fafc;
        padding: 12px;
        border-radius: 6px;
        border-left: 4px solid #3b82f6;
      }
      .vocab-list {
        display: flex;
        flex-direction: column;
        gap: 15px;
      }
      .vocab-item {
        background: #fff;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        page-break-inside: avoid;
      }
      .vocab-header {
        display: flex;
        align-items: center;
        gap: 10px;
        margin-bottom: 8px;
        border-bottom: 1px solid #f1f5f9;
        padding-bottom: 8px;
      }
      .vocab-number {
        background: #eff6ff;
        color: #2563eb;
        padding: 2px 6px;
        border-radius: 4px;
        font-size: 12px;
        font-weight: bold;
      }
      .vocab-word {
        font-size: 18px;
        font-weight: bold;
        color: #1e293b;
      }
      .vocab-pos {
        font-style: italic;
        color: #64748b;
        font-size: 14px;
      }
      .vocab-body p {
        margin: 4px 0;
        font-size: 14px;
      }
      .vocab-meaning {
        color: #0f172a;
      }
      .vocab-example {
        color: #475569;
        font-style: italic;
        margin-top: 8px !important;
        background: #f8fafc;
        padding: 8px;
        border-radius: 4px;
      }
      .footer {
        text-align: center;
        font-size: 12px;
        color: #9ca3af;
        margin-top: 30px;
        padding-top: 16px;
        border-top: 1px solid #e5e7eb;
      }
      .generated-at {
        font-size: 11px;
        color: #d1d5db;
        margin-top: 4px;
      }
    `;
    pdfElement.appendChild(style);

    // Configure html2pdf options
    const opt = {
      margin: [0.5, 0.5, 0.5, 0.5],
      filename: `vocabulary-favorites-${format(new Date(), "yyyy-MM-dd")}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: {
        scale: 2,
        useCORS: true,
        letterRendering: true,
      },
      jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
    };

    await html2pdf().set(opt).from(pdfElement).save();

    // Clean up
    document.body.removeChild(pdfElement);
    return true;
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw error;
  }
};
